export * from './car.interface';
export * from './configsInterfaces/urls.interface';
export * from './servicesInterfaces/carCervice.interface';
export * from './propsInterfaces/carProps.interface';
export * from './stateSlicesInterfaces/stateCar.interface';
export * from './actionsInterfaces/setCars.interface';
export * from './actionsInterfaces/addCar.interface';
export * from './actionsInterfaces/updateCarWithIndex.interface';
export * from './actionsInterfaces/deleteCar.interface';
export * from './actionsInterfaces/updateCar.interface';
export * from './actionsInterfaces/deleteCarWithIndex.interface'